[env:glyph-c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
build_src_filter = +<main.cpp>

board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
board_build.embed_files =
    assets/Modern User Interface Sound Effects (Copyright Free).mp3
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_port = /dev/cu.usbmodem1301
monitor_port = /dev/cu.usbmodem1301

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=0
    -I .pio/libdeps/glyph-c6/libopus/src/oggz

lib_deps =
    pcbcupid/PCBCUPID_PLAYERS@1.0.2
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pcbcupid/arduino-audio-driver.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/pschatzmann/arduino-libopus.git
    h2zero/NimBLE-Arduino@^2.3.7

[env:nfc-test]
extends = env:glyph-c6
build_src_filter = +<nfc_test.cpp>
