const SERVICE_UUID="7e400001-b5a3-f393-e0a9-e50e24dcca9e",COMMAND_UUID="7e400002-b5a3-f393-e0a9-e50e24dcca9e",EVENTS_UUID="7e400003-b5a3-f393-e0a9-e50e24dcca9e";
const $=s=>document.querySelector(s),decoder=new TextDecoder(),encoder=new TextEncoder();
let device,commandCharacteristic,eventCharacteristic,tracks=[],mappings=new Map(),currentUid="",currentPlaylist=[];
const activity=m=>$("#activity").textContent=m;
const prettyUid=u=>u.match(/.{1,2}/g)?.join(":")??u;
const basename=p=>p.split("/").filter(Boolean).at(-1)||p;
async function send(c){if(!commandCharacteristic)throw new Error("Player is not connected");await commandCharacteristic.writeValueWithoutResponse(encoder.encode(c))}
function setConnected(c){$("#statusDot").classList.toggle("connected",c);$("#connectionStatus").textContent=c?"Player connected":"Not connected";$("#connectButton").textContent=c?"Reconnect":"Connect player";$("#refreshButton").disabled=!c;updateActions()}
async function connect(){if(!("bluetooth"in navigator))throw new Error("Web Bluetooth is unavailable. Use Chrome or Edge on Android or desktop.");activity("Choose “Glyph Soundbox” in the Bluetooth picker…");device=await navigator.bluetooth.requestDevice({filters:[{services:[SERVICE_UUID]}]});device.addEventListener("gattserverdisconnected",()=>{setConnected(false);activity("Player disconnected.")});const server=await device.gatt.connect(),service=await server.getPrimaryService(SERVICE_UUID);commandCharacteristic=await service.getCharacteristic(COMMAND_UUID);eventCharacteristic=await service.getCharacteristic(EVENTS_UUID);await eventCharacteristic.startNotifications();eventCharacteristic.addEventListener("characteristicvaluechanged",onEvent);setConnected(true);$("#deviceStatus").textContent=device.name||"Glyph Soundbox";activity("Connected. Loading SD library and saved mappings…");for(const c of["HELLO","STATUS","TRACKS","MAPS"])await send(c)}
function csvToPlaylist(csv){return csv?csv.split(",").map(Number).filter(Number.isInteger):[]}
function onEvent(event){const message=decoder.decode(event.target.value);activity(message);const[type,...parts]=message.split("|");if(type==="TRACKS_BEGIN")tracks=[];else if(type==="TRACK")tracks[Number(parts[0])]=parts.slice(1).join("|");else if(type==="TRACKS_END")renderLibrary();else if(type==="MAPS_BEGIN")mappings=new Map();else if(type==="MAP"){mappings.set(parts[0],csvToPlaylist(parts[1]||""));if(currentUid===parts[0])selectCard(parts[0])}else if(type==="CARD"||type==="AUTO_MAPPED")selectCard(parts[0]);else if(type==="SAVED"){mappings.set(parts[0],csvToPlaylist(parts[1]||""));selectCard(parts[0]);activity(`Playlist saved for ${prettyUid(parts[0])}.`)}else if(type==="CLEARED"){mappings.delete(parts[0]);if(currentUid===parts[0])currentPlaylist=[];renderPlaylist()}else if(type==="STATUS"){$("#deviceStatus").textContent=`${parts[0]} · ${parts[1]} · ${parts[2]} MP3 track(s)`;if(parts[3]&&parts[3]!=="NO_CARD")selectCard(parts[3])}}
function selectCard(uid){currentUid=uid;currentPlaylist=[...(mappings.get(uid)||[])];$("#cardUid").textContent=prettyUid(uid);renderPlaylist();updateActions()}
function renderLibrary(){const root=$("#library");root.classList.toggle("empty",tracks.length===0);root.replaceChildren();$("#trackCount").textContent=tracks.length;if(!tracks.length){root.textContent="No MP3 files found on the SD card.";return}tracks.forEach((path,index)=>{if(path==null)return;const item=$("#libraryItemTemplate").content.firstElementChild.cloneNode(true);item.querySelector(".track-index").textContent=String(index+1).padStart(2,"0");item.querySelector(".track-name").textContent=basename(path);item.title=path;item.addEventListener("click",()=>{if(!currentUid)return activity("Tap an NFC card on the player first.");currentPlaylist.push(index);renderPlaylist()});root.append(item)})}
function renderPlaylist(){const root=$("#playlist");root.classList.toggle("empty",currentPlaylist.length===0);root.replaceChildren();$("#playlistCount").textContent=currentPlaylist.length;if(!currentPlaylist.length){root.textContent=currentUid?"Add tracks from the library.":"Tap a card, then add tracks.";updateActions();return}currentPlaylist.forEach((trackIndex,position)=>{const item=$("#playlistItemTemplate").content.firstElementChild.cloneNode(true);item.querySelector(".track-name").textContent=`${position+1}. ${basename(tracks[trackIndex]||`Track ${trackIndex}`)}`;item.querySelector(".up").disabled=position===0;item.querySelector(".down").disabled=position===currentPlaylist.length-1;item.querySelector(".up").addEventListener("click",()=>move(position,-1));item.querySelector(".down").addEventListener("click",()=>move(position,1));item.querySelector(".remove").addEventListener("click",()=>{currentPlaylist.splice(position,1);renderPlaylist()});root.append(item)});updateActions()}
function move(position,offset){const target=position+offset;[currentPlaylist[position],currentPlaylist[target]]=[currentPlaylist[target],currentPlaylist[position]];renderPlaylist()}
function updateActions(){const connected=Boolean(commandCharacteristic&&device?.gatt?.connected);$("#saveButton").disabled=!connected||!currentUid||!currentPlaylist.length;$("#clearButton").disabled=!connected||!currentUid}
$("#connectButton").addEventListener("click",()=>connect().catch(e=>activity(e.message)));$("#refreshButton").addEventListener("click",async()=>{tracks=[];await send("TRACKS");await send("MAPS")});$("#saveButton").addEventListener("click",()=>send(`MAP|${currentUid}|${currentPlaylist.join(",")}`).catch(e=>activity(e.message)));$("#clearButton").addEventListener("click",()=>send(`CLEAR|${currentUid}`).catch(e=>activity(e.message)));if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");
